[build]
  command = "echo 'Skipping build process'"
  publish = "/opt/build/repo/netlify.toml"
[[redirects]]
  from = "/reverse-proxy/*"
  to = "/.netlify/functions/reverse-proxy/:splat"
  status = 200
